#!/bin/bash

export REGISTRY="ec2-52-39-179-208.us-west-2.compute.amazonaws.com:5000"
export IMAGE=$(sed -n '1p' /tmp/.auth)
export TAG=$(sed -n '2p' /tmp/.auth)
#export PASS=$(sed -n '3p' /tmp/.auth)

#docker login -u user1 -p $PASS $REGISTRY
cd ~/jenkins/ && docker-compose up -d
